In [45]:
# Basic Import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns

In [46]:
StudentAcadPerformance=pd.read_csv('StudentAcadPerformance.csv')

In [47]:
StudentAcadPerformance.shape

(729, 40)

In [48]:
StudentAcadPerformance.head()

,Gender,MaritalStatus,Age,Accommodation,Faculty,SecSchType,HealthCondition,LevelOfStudy,LectureAttend,ClassActive,...,ClassSize,InternetAccess,LecClarification,LecSupport,TeachnApproach,TeachnResources,TopicDensity,LecAbsFreq,LecPuctuality,TeachExperience
0,Male,Single,31-35,Living with family/relatives,Physical Sciences,Public,No,500,Strongly disagree,Occasionally,...,Yes,Strongly disagree,Good,Good,Occasionally,Frequently,Disagree,Disagree,Agree,Good
1,Male,Single,31-35,Off-campus,Physical Sciences,Public,No,500,Disagree,Frequently,...,Yes,Strongly disagree,Good,Good,Frequently,Frequently,Agree,Agree,Agree,Good
2,Male,Single,21-25,Off-campus,Physical Sciences,Private,No,300,Agree,Never,...,No,Strongly disagree,Average,Good,Occasionally,Never,Agree,Agree,Strongly agree,Excellent
3,Female,Single,21-25,On-campus,Life Sciences,Public,No,500,Disagree,Never,...,Yes,Agree,Good,Excellent,Always,Always,Disagree,Disagree,Disagree,Excellent
4,Male,Single,16-20,Off-campus,Physical Sciences,Private,No,200,Agree,Rarely,...,Yes,Disagree,Average,Good,Occasionally,Occasionally,Disagree,Strongly disagree,Disagree,Good

In [49]:
StudentAcadPerformance['CGPA']

0      3.50 - 4.49
1      3.50 - 4.49
2      2.40 - 3.49
3      1.50 - 2.39
4      2.40 - 3.49
          ...
724    2.40 - 3.49
725    2.40 - 3.49
726    3.50 - 4.49
727    2.40 - 3.49
728    1.50 - 2.39
Name: CGPA, Length: 729, dtype: object

In [50]:
CGPA=StudentAcadPerformance['CGPA'].replace(["0.00 - 1.49", "1.50 - 2.39", "2.40 - 3.49", "3.50 - 4.49", "4.50 - 5.00"], [0, 0, 0, 1, 1], inplace=True)
CGPA

In [51]:
StudentAcadPerformance=pd.get_dummies(StudentAcadPerformance, drop_first=True)
StudentAcadPerformance

,LevelOfStudy,CGPA,Gender_Male,MaritalStatus_Married,MaritalStatus_Single,MaritalStatus_Widowed,Age_21-25,Age_26-30,Age_31-35,Age_36 or above,...,LecAbsFreq_Disagree,LecAbsFreq_Strongly agree,LecAbsFreq_Strongly disagree,LecPuctuality_Disagree,LecPuctuality_Strongly agree,LecPuctuality_Strongly disagree,TeachExperience_Excellent,TeachExperience_Good,TeachExperience_Poor,TeachExperience_Very poor
0,500,1,True,False,True,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,False
1,500,1,True,False,True,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
2,300,0,True,False,True,False,True,False,False,False,...,False,False,False,False,True,False,True,False,False,False
3,500,0,False,False,True,False,True,False,False,False,...,True,False,False,True,False,False,True,False,False,False
4,200,0,True,False,True,False,False,False,False,False,...,False,False,True,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,300,0,True,False,True,False,True,False,False,False,...,False,False,False,True,False,False,True,False,False,False
725,500,0,True,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
726,200,1,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
727,300,0,True,False,True,False,False,True,False,False,...,False,True,False,True,False,False,False,True,False,False
728,400,0,True,False,True,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False

In [52]:
StudentAcadPerformance=pd.get_dummies(StudentAcadPerformance, drop_first=True)
StudentAcadPerformance

,LevelOfStudy,CGPA,Gender_Male,MaritalStatus_Married,MaritalStatus_Single,MaritalStatus_Widowed,Age_21-25,Age_26-30,Age_31-35,Age_36 or above,...,LecAbsFreq_Disagree,LecAbsFreq_Strongly agree,LecAbsFreq_Strongly disagree,LecPuctuality_Disagree,LecPuctuality_Strongly agree,LecPuctuality_Strongly disagree,TeachExperience_Excellent,TeachExperience_Good,TeachExperience_Poor,TeachExperience_Very poor
0,500,1,True,False,True,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,False
1,500,1,True,False,True,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
2,300,0,True,False,True,False,True,False,False,False,...,False,False,False,False,True,False,True,False,False,False
3,500,0,False,False,True,False,True,False,False,False,...,True,False,False,True,False,False,True,False,False,False
4,200,0,True,False,True,False,False,False,False,False,...,False,False,True,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,300,0,True,False,True,False,True,False,False,False,...,False,False,False,True,False,False,True,False,False,False
725,500,0,True,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
726,200,1,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
727,300,0,True,False,True,False,False,True,False,False,...,False,True,False,True,False,False,False,True,False,False
728,400,0,True,False,True,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False

In [53]:
StudentAcadPerformance

,LevelOfStudy,CGPA,Gender_Male,MaritalStatus_Married,MaritalStatus_Single,MaritalStatus_Widowed,Age_21-25,Age_26-30,Age_31-35,Age_36 or above,...,LecAbsFreq_Disagree,LecAbsFreq_Strongly agree,LecAbsFreq_Strongly disagree,LecPuctuality_Disagree,LecPuctuality_Strongly agree,LecPuctuality_Strongly disagree,TeachExperience_Excellent,TeachExperience_Good,TeachExperience_Poor,TeachExperience_Very poor
0,500,1,True,False,True,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,False
1,500,1,True,False,True,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
2,300,0,True,False,True,False,True,False,False,False,...,False,False,False,False,True,False,True,False,False,False
3,500,0,False,False,True,False,True,False,False,False,...,True,False,False,True,False,False,True,False,False,False
4,200,0,True,False,True,False,False,False,False,False,...,False,False,True,True,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,300,0,True,False,True,False,True,False,False,False,...,False,False,False,True,False,False,True,False,False,False
725,500,0,True,False,True,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
726,200,1,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
727,300,0,True,False,True,False,False,True,False,False,...,False,True,False,True,False,False,False,True,False,False
728,400,0,True,False,True,False,False,True,False,False,...,False,False,False,False,False,False,False,True,False,False

In [54]:
StudentAcadPerformance=StudentAcadPerformance.replace([True,False],[1,0])
StudentAcadPerformance

,LevelOfStudy,CGPA,Gender_Male,MaritalStatus_Married,MaritalStatus_Single,MaritalStatus_Widowed,Age_21-25,Age_26-30,Age_31-35,Age_36 or above,...,LecAbsFreq_Disagree,LecAbsFreq_Strongly agree,LecAbsFreq_Strongly disagree,LecPuctuality_Disagree,LecPuctuality_Strongly agree,LecPuctuality_Strongly disagree,TeachExperience_Excellent,TeachExperience_Good,TeachExperience_Poor,TeachExperience_Very poor
0,500,1,1,0,1,0,0,0,1,0,...,1,0,0,0,0,0,0,1,0,0
1,500,1,1,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2,300,0,1,0,1,0,1,0,0,0,...,0,0,0,0,1,0,1,0,0,0
3,500,0,0,0,1,0,1,0,0,0,...,1,0,0,1,0,0,1,0,0,0
4,200,0,1,0,1,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,300,0,1,0,1,0,1,0,0,0,...,0,0,0,1,0,0,1,0,0,0
725,500,0,1,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
726,200,1,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
727,300,0,1,0,1,0,0,1,0,0,...,0,1,0,1,0,0,0,1,0,0
728,400,0,1,0,1,0,0,1,0,0,...,0,0,0,0,0,0,0,1,0,0

In [55]:
StudentAcadPerformance.drop([' LevelOfStudy'], axis=1 , inplace=True)

In [62]:
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor,AdaBoostRegressor
from sklearn.svm import SVR
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostRegressor
from xgboost import XGBRegressor
import warnings

In [56]:
y=StudentAcadPerformance['CGPA']
X = StudentAcadPerformance.drop(columns=['CGPA'],axis=1)
X

,Gender_Male,MaritalStatus_Married,MaritalStatus_Single,MaritalStatus_Widowed,Age_21-25,Age_26-30,Age_31-35,Age_36 or above,Accommodation_Off-campus,Accommodation_On-campus,...,LecAbsFreq_Disagree,LecAbsFreq_Strongly agree,LecAbsFreq_Strongly disagree,LecPuctuality_Disagree,LecPuctuality_Strongly agree,LecPuctuality_Strongly disagree,TeachExperience_Excellent,TeachExperience_Good,TeachExperience_Poor,TeachExperience_Very poor
0,1,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,1,0,0
1,1,0,1,0,0,0,1,0,1,0,...,0,0,0,0,0,0,0,1,0,0
2,1,0,1,0,1,0,0,0,1,0,...,0,0,0,0,1,0,1,0,0,0
3,0,0,1,0,1,0,0,0,0,1,...,1,0,0,1,0,0,1,0,0,0
4,1,0,1,0,0,0,0,0,1,0,...,0,0,1,1,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
724,1,0,1,0,1,0,0,0,0,0,...,0,0,0,1,0,0,1,0,0,0
725,1,0,1,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
726,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
727,1,0,1,0,0,1,0,0,1,0,...,0,1,0,1,0,0,0,1,0,0
728,1,0,1,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,1,0,0

In [57]:
# Create Column Transformer with 3 types of transformers
num_features = X.select_dtypes(exclude="object").columns
cat_features = X.select_dtypes(include="object").columns

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder()

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, cat_features),
         ("StandardScaler", numeric_transformer, num_features),        
    ]
)

In [58]:
X = preprocessor.fit_transform(X)

In [59]:
# separate dataset into train and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((583, 115), (146, 115))

In [65]:
model_lg= LogisticRegression()
model_ls= Lasso()
model_rd= Ridge()
model_KN= KNeighborsRegressor(n_neighbors=3)
model_dt= DecisionTreeClassifier()
model_RfR= RandomForestRegressor()
model_ABR=AdaBoostRegressor()

NameError: name 'LogisticRegression' is not defined

In [66]:
model_lg.fit(X_train, y_train)
model_ls.fit(X_train, y_train)
model_rd.fit(X_train, y_train)
model_KN.fit(X_train, y_train)
model_dt.fit(X_train, y_train)
model_RfR.fit(X_train, y_train)
Model_AR.fit(X_train, y_train)
model_ABR.fit(X_train, y_train)

NameError: name 'model_lg' is not defined

In [67]:
model_lg_pred = model_lg.predict(X_test)
model_ls_pred=model_ls.predict(X_test)
model_rd_pred=model_lg.predict(X_test)
model_KN_pred=model_rd.predict(X_test)
model_dt_pred=model_dt.predict(X_test)
model_RfR_pred=model_RfR.predict(X_test)
model_ABR_pred=model_ABR.predict(X_test)

NameError: name 'model_lg' is not defined

In [ ]:
model_lg_accuracy=accuracy_score(y_test, model_lg_pred)
# model_ls_accuracy=accuracy_score(y_test, model_ls_pred)
model_rd_accuracy=accuracy_score(y_test, model_rd_pred)
# model_KN_accuracy=accuracy_score(y_test, model_KN_pred)
model_dt_accuracy=accuracy_score(y_test, model_dt_pred)
# model_RfR_accuracy=accuracy_score(y_test, model_RfR_pred)
# model_ABR_accuracy=accuracy_score(y_test, model_ABR_pred)
print(model_lg_accuracy)
print(model_rd_accuracy)
print(model_dt_accuracy)